name: Tests
on:
  push:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: apt-get -y install luajit
      - run: luarocks --lua-version 5.1 install busted
      - run: busted
