name: Tests
on:
  push:
    branches:
      - main
jobs:
  unit-test:
    runs-on: akorn/luarocks:lua5.1-alpine
    steps:
      - uses: actions/checkout@v4
      - run: luarocks install busted
      - run: busted
